# Generated by Django 4.1.2 on 2022-10-26 09:54

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('district', models.CharField(blank=True, max_length=128, null=True)),
                ('street', models.CharField(max_length=256)),
                ('street_number', models.CharField(max_length=16)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('build_year', models.IntegerField()),
                ('total_floors', models.IntegerField()),
                ('address', models.ForeignKey(db_column='address_uid', on_delete=django.db.models.deletion.CASCADE, related_name='buildings', related_query_name='building', to='flats.address')),
            ],
            options={
                'db_table': 'flat',
            },
        ),
        migrations.CreateModel(
            name='Residential',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=256, populate_from='name', unique=True)),
            ],
            options={
                'db_table': 'residentials',
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rooms', models.IntegerField()),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=7)),
                ('living_area', models.DecimalField(decimal_places=2, max_digits=7)),
                ('kitchen_area', models.DecimalField(decimal_places=2, max_digits=7)),
                ('floor', models.IntegerField()),
                ('flat_number', models.CharField(max_length=8)),
                ('building', models.ForeignKey(db_column='residential_uid', on_delete=django.db.models.deletion.CASCADE, related_name='buildings', related_query_name='building', to='flats.building')),
            ],
            options={
                'db_table': 'flats',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='residential',
            field=models.ForeignKey(blank=True, db_column='residential_uid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buildings', related_query_name='building', to='flats.residential'),
        ),
    ]
